service: ${env:SERVICE_NAME}

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE}
  region: ${env:REGION}
  environment:
    AUTH0_AUDIENCE: ${env:AUTH0_AUDIENCE}
    AUTH0_DOMAIN: ${env:AUTH0_DOMAIN}

functions:
  app:
    handler: index.handler
    cors: true
